/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cbtquiz_csc301;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Samsung
 */
public class CBTQuiz extends javax.swing.JFrame {

    String[] Answer = {"Java",
        "Google",
        "Central Processing Unit",
        "Python",
        "Routing data packets",
        "JavaScript",
        "Hypertext Markup Language",
        "Amazon",
        "Identifying devices on a network",
        "R"};
    String[] userAnswer = {"", "", "", "", "", "", "", "", "", "", ""};
    String yourOption = "";
    String[] questions = {
        "What is the most used popular programming language?",
        "Which company developed the Android operating system?",
        "What does CPU stand for?",
        "Which programming language is known for its use in machine learning?",
        "What is the primary function of a router in a computer network?",
        "Which programming language is used for front-end web development?",
        "What does HTML stand for?",
        "Which company is known for its cloud computing platform, AWS?",
        "What is the purpose of an IP address?",
        "Which programming language is often used for data analysis and scientific computing?"
    };

    String[] optionA = {
        "Java",
        "Google",
        "Central Processing Unit",
        "Python",
        "Routing data packets",
        "JavaScript",
        "Hypertext Markup Language",
        "Amazon",
        "Identifying devices on a network",
        "R"
    };

    String[] optionB = {
        "Python",
        "Apple",
        "Central Process Unit",
        "C++",
        "Providing internet access",
        "Python",
        "Hyper Transfer Markup Language",
        "Microsoft",
        "Providing physical addresses for devices",
        "Java"
    };

    String[] optionC = {
        "JavaScript",
        "Microsoft",
        "Central Processor Unit",
        "Java",
        "Filtering spam emails",
        "PHP",
        "Hyper Text Markup Language",
        "Oracle",
        "Securing network communications",
        "JavaScript"
    };

    String[] optionD = {
        "C++",
        "Oracle",
        "Central Process Unit",
        "Ruby",
        "Translating languages in real-time",
        "Ruby",
        "Hypertext Transfer Markup Language",
        "IBM",
        "Transmitting voice over the internet",
        "C#"
    };
    int i = 0;
    int score = 0;
    int timeRemaining = 60;

    /**
     * Creates new form CBTQuiz
     */
    public int getScore() {
        return score;
    }

    public CBTQuiz() {
        initComponents();
        jTextArea1.setText(questions[i]);
        jRadioButton1.setText(optionA[i]);
        jRadioButton2.setText(optionB[i]);
        jRadioButton3.setText(optionC[i]);
        jRadioButton4.setText(optionD[i]);

        //date & time      
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get the current time
                Date currentTime = new Date();

                // Create a SimpleDateFormat object to format the time
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy  HH:mm:ss"); // Customize the format as needed

                // Format the time as a String and set it to the JLabel
                jDate.setText(sdf.format(currentTime));
            }
        });
        timer.start();
        
        //TIMER
        Timer countdownTimer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (timeRemaining > 0) {
                    --timeRemaining;
                    jTimer.setText("Time Remaining: " + timeRemaining + " seconds");
                } else {
                    // Time has elapsed, automatically submit the quiz
                    
                    
                    ((Timer) e.getSource()).stop(); // Stop the timer
                    jNext.setEnabled(false);
                    jPrevious.setEnabled(false);
                            
                }
            }
        });
        countdownTimer.start();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jNext = new javax.swing.JButton();
        jPrevious = new javax.swing.JButton();
        jSubmit = new javax.swing.JButton();
        jTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CBT QUIZ");

        jDate.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jDate.setForeground(new java.awt.Color(255, 255, 255));
        jDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDate.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jDate)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("jRadioButton2");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton3.setText("jRadioButton3");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton4.setText("jRadioButton4");

        jNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jNext.setText("Next");
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });

        jPrevious.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPrevious.setText("Previous");
        jPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPreviousActionPerformed(evt);
            }
        });

        jSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jTimer.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTimer.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTimer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton2))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jNext)
                .addGap(123, 123, 123)
                .addComponent(jPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSubmit)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(44, 44, 44)
                .addComponent(jTimer)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNext)
                    .addComponent(jPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSubmit))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(414, 414, 414))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        if (i == (questions.length - 1)) {
            JOptionPane.showMessageDialog(null, "This is the last question");

        } else {
            if (jRadioButton1.isSelected()) {
                yourOption = jRadioButton1.getText(); //text of jradiobutton would be stored in yourOption, 
                //then would be stored in the array Useranswer
                userAnswer[i] = yourOption;
            } else if (jRadioButton2.isSelected()) {
                yourOption = jRadioButton2.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton3.isSelected()) {
                yourOption = jRadioButton3.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton4.isSelected()) {
                yourOption = jRadioButton4.getText();
                userAnswer[i] = yourOption;
            }

            i = i + 1;

            jTextArea1.setText(questions[i]);
            jRadioButton1.setText(optionA[i]);
            jRadioButton2.setText(optionB[i]);
            jRadioButton3.setText(optionC[i]);
            jRadioButton4.setText(optionD[i]);
            buttonGroup1.clearSelection();

            if (userAnswer[i] == jRadioButton1.getText()) {
                jRadioButton1.setSelected(true);
            } else if (userAnswer[i] == jRadioButton2.getText()) {
                jRadioButton2.setSelected(true);
            } else if (userAnswer[i] == jRadioButton3.getText()) {
                jRadioButton3.setSelected(true);
            } else if (userAnswer[i] == jRadioButton4.getText()) {
                jRadioButton4.setSelected(true);
            }// TODO add your handling code here:
    }//GEN-LAST:event_jNextActionPerformed
    }

    private void jPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPreviousActionPerformed
        if (i == 0) {
            JOptionPane.showMessageDialog(null, "This is the first question");

            if (jRadioButton1.isSelected()) {
                yourOption = jRadioButton1.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton2.isSelected()) {
                yourOption = jRadioButton2.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton3.isSelected()) {
                yourOption = jRadioButton3.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton4.isSelected()) {
                yourOption = jRadioButton4.getText();
                userAnswer[i] = yourOption;
            }

        } else {
            if (jRadioButton1.isSelected()) {
                yourOption = jRadioButton1.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton2.isSelected()) {
                yourOption = jRadioButton2.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton3.isSelected()) {
                yourOption = jRadioButton3.getText();
                userAnswer[i] = yourOption;
            } else if (jRadioButton4.isSelected()) {
                yourOption = jRadioButton4.getText();
                userAnswer[i] = yourOption;
            }
            i = i - 1;

            jTextArea1.setText(questions[i]);
            jRadioButton1.setText(optionA[i]);
            jRadioButton2.setText(optionB[i]);
            jRadioButton3.setText(optionC[i]);
            jRadioButton4.setText(optionD[i]);
            buttonGroup1.clearSelection();

            if (userAnswer[i] == jRadioButton1.getText()) {
                jRadioButton1.setSelected(true);
            } else if (userAnswer[i] == jRadioButton2.getText()) {
                jRadioButton2.setSelected(true);
            } else if (userAnswer[i] == jRadioButton3.getText()) {
                jRadioButton3.setSelected(true);
            } else if (userAnswer[i] == jRadioButton4.getText()) {
                jRadioButton4.setSelected(true);
            }
            // TODO add your handling code here:
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jPreviousActionPerformed

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        if (jRadioButton1.isSelected()) {
            yourOption = jRadioButton1.getText(); //text of jradiobutton would be stored in yourOption, 
            //then would be stored in the array Useranswer
            userAnswer[i] = yourOption;
        } else if (jRadioButton2.isSelected()) {
            yourOption = jRadioButton2.getText();
            userAnswer[i] = yourOption;
        } else if (jRadioButton3.isSelected()) {
            yourOption = jRadioButton3.getText();
            userAnswer[i] = yourOption;
        } else if (jRadioButton4.isSelected()) {
            yourOption = jRadioButton4.getText();
            userAnswer[i] = yourOption;
        }

        if (userAnswer[i] == jRadioButton1.getText()) {
            jRadioButton1.setSelected(true);
        } else if (userAnswer[i] == jRadioButton2.getText()) {
            jRadioButton2.setSelected(true);
        } else if (userAnswer[i] == jRadioButton3.getText()) {
            jRadioButton3.setSelected(true);
        } else if (userAnswer[i] == jRadioButton4.getText()) {
            jRadioButton4.setSelected(true);
        }

        String answer;
        String uanswer;

        for (i = 0; i < questions.length; i++) {
            answer = Answer[i];
            uanswer = userAnswer[i];

            if (uanswer == answer) {
                score = score + 5;
            } else {
                score = score + 0;
            }

        }// TODO add your handling code here:
        Result jfrm1 = new Result();
        jfrm1.setSize(300, 400);
        jfrm1.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
        score = getScore();
        jfrm1.setScore(score);

        // Initial time in seconds (e.g., 10 minutes)

    }//GEN-LAST:event_jSubmitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CBTQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CBTQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CBTQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CBTQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBTQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jPrevious;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSubmit;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jTimer;
    // End of variables declaration//GEN-END:variables
}
