/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package addition_calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    double NumEnter1;
    double NumEnter2;
    double result;
    String op;
    
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonADD = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonDIVIDE = new javax.swing.JButton();
        jButtonSUBTRACT = new javax.swing.JButton();
        jButtonMULTIPLY = new javax.swing.JButton();
        jButtonCLEAR = new javax.swing.JButton();
        jButtonNUM1 = new javax.swing.JButton();
        jButtonNUM7 = new javax.swing.JButton();
        jButtonNUM2 = new javax.swing.JButton();
        jButtonNUM6 = new javax.swing.JButton();
        jButtonNUM3 = new javax.swing.JButton();
        jButtonNUM8 = new javax.swing.JButton();
        jButtonNUM4 = new javax.swing.JButton();
        jButtonNUM9 = new javax.swing.JButton();
        jButtonNUM5 = new javax.swing.JButton();
        jButtonNUM0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonSOLVE = new javax.swing.JButton();
        jButtonDECIMAL = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jButtonADD.setText("ADD");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel5.setText("Calculator");

        jButtonDIVIDE.setText("DIVIDE");
        jButtonDIVIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDIVIDEActionPerformed(evt);
            }
        });

        jButtonSUBTRACT.setText("SUBTRACT");
        jButtonSUBTRACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSUBTRACTActionPerformed(evt);
            }
        });

        jButtonMULTIPLY.setText("MULTIPLY");
        jButtonMULTIPLY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMULTIPLYActionPerformed(evt);
            }
        });

        jButtonCLEAR.setText("CLEAR");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });

        jButtonNUM1.setText("1");
        jButtonNUM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNUM1MouseClicked(evt);
            }
        });
        jButtonNUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM1ActionPerformed(evt);
            }
        });

        jButtonNUM7.setText("7");
        jButtonNUM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNUM7MouseClicked(evt);
            }
        });
        jButtonNUM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM7ActionPerformed(evt);
            }
        });
        jButtonNUM7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNUM7KeyPressed(evt);
            }
        });

        jButtonNUM2.setText("2");
        jButtonNUM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM2ActionPerformed(evt);
            }
        });

        jButtonNUM6.setText("6");
        jButtonNUM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM6ActionPerformed(evt);
            }
        });

        jButtonNUM3.setText("3");
        jButtonNUM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM3ActionPerformed(evt);
            }
        });

        jButtonNUM8.setText("8");
        jButtonNUM8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM8ActionPerformed(evt);
            }
        });

        jButtonNUM4.setText("4");
        jButtonNUM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM4ActionPerformed(evt);
            }
        });

        jButtonNUM9.setText("9");
        jButtonNUM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM9ActionPerformed(evt);
            }
        });

        jButtonNUM5.setText("5");
        jButtonNUM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM5ActionPerformed(evt);
            }
        });

        jButtonNUM0.setText("0");
        jButtonNUM0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM0ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonSOLVE.setText("SOLVE");
        jButtonSOLVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSOLVEActionPerformed(evt);
            }
        });

        jButtonDECIMAL.setText(".");
        jButtonDECIMAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDECIMALActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonNUM3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonNUM4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonNUM6)))
                                .addGap(79, 79, 79))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonNUM1)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonNUM2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonDECIMAL))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonNUM9)
                                            .addComponent(jButtonNUM5)
                                            .addComponent(jButtonNUM8))
                                        .addGap(161, 161, 161))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonNUM7)
                                .addGap(113, 113, 113)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSOLVE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSUBTRACT)
                            .addComponent(jButtonADD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMULTIPLY, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDIVIDE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNUM0)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNUM1)
                    .addComponent(jButtonNUM2)
                    .addComponent(jButtonNUM3)
                    .addComponent(jButtonSUBTRACT)
                    .addComponent(jButtonDECIMAL))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNUM6)
                    .addComponent(jButtonNUM4)
                    .addComponent(jButtonNUM5)
                    .addComponent(jButtonADD))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNUM7)
                    .addComponent(jButtonNUM8)
                    .addComponent(jButtonMULTIPLY)
                    .addComponent(jButtonCLEAR))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNUM0)
                    .addComponent(jButtonNUM9)
                    .addComponent(jButtonDIVIDE)
                    .addComponent(jButtonSOLVE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void EnterNumbers(String q)
{
    String Nums = jTextArea1.getText() + q;
    jTextArea1.setText(Nums);
}  

    private void jButtonDECIMALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDECIMALActionPerformed
        if (!jTextArea1.getText().contains(".")){
            jTextArea1.setText(jTextArea1.getText() + jButtonDECIMAL.getText())  ;
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDECIMALActionPerformed

    private void jButtonSOLVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSOLVEActionPerformed
        NumEnter2 = Double.parseDouble(jTextArea1.getText());
        if (op == "+"){
            result = NumEnter1 + NumEnter2;
            String res = Double.toString(result);
            jTextArea1.setText(res);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSOLVEActionPerformed
      else if (op == "-"){
result = NumEnter1 - NumEnter2;
String res = Double.toString(result);
jTextArea1.setText(res);// TODO add your handling code here:
    }  
    
  else if (op == "*"){
result = NumEnter1 * NumEnter2;
String res = Double.toString(result);
jTextArea1.setText(res);// TODO add your handling code here:
    }  
    
      else if (op == "/"){
result = NumEnter1 / NumEnter2;
String res = Double.toString(result);
jTextArea1.setText(res);// TODO add your handling code here:
    }  
    
    }
    private void jButtonNUM0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM0ActionPerformed
        EnterNumbers("0");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM0ActionPerformed

    private void jButtonNUM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM5ActionPerformed
        EnterNumbers("5");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM5ActionPerformed

    private void jButtonNUM9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM9ActionPerformed
        EnterNumbers("9");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM9ActionPerformed

    private void jButtonNUM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM4ActionPerformed
        EnterNumbers("4");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM4ActionPerformed

    private void jButtonNUM8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM8ActionPerformed
        EnterNumbers("8");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM8ActionPerformed

    private void jButtonNUM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM3ActionPerformed
        EnterNumbers("3");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM3ActionPerformed

    private void jButtonNUM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM6ActionPerformed
        EnterNumbers("6");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM6ActionPerformed

    private void jButtonNUM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM2ActionPerformed
        EnterNumbers("2");     // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM2ActionPerformed

    private void jButtonNUM7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNUM7KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM7KeyPressed

    private void jButtonNUM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM7ActionPerformed
        EnterNumbers("7");          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM7ActionPerformed

    private void jButtonNUM7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNUM7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM7MouseClicked

    private void jButtonNUM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUM1ActionPerformed
        EnterNumbers("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM1ActionPerformed

    private void jButtonNUM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNUM1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUM1MouseClicked

    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed
        jTextArea1.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void jButtonMULTIPLYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMULTIPLYActionPerformed
        NumEnter1 = Double.parseDouble(jTextArea1.getText());
        jTextArea1.setText("");
        op = "*";  /* try{
            String a = jTextField4.getText();// TODO add your handling code here:
            String b = jTextField5.getText();
            int no1=Integer.parseInt(a);
            int no2=Integer.parseInt(b);

            int res = no1 * no2;
            String result=String.valueOf(res);
            jTextField6.setText(result);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Enter appropriate values");

        }    */ // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMULTIPLYActionPerformed

    private void jButtonSUBTRACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSUBTRACTActionPerformed
        NumEnter1 = Double.parseDouble(jTextArea1.getText());
        jTextArea1.setText("");
        op = "- ";/*try{
            String a = jTextField4.getText();// TODO add your handling code here:
            String b = jTextField5.getText();
            int no1=Integer.parseInt(a);
            int no2=Integer.parseInt(b);

            int res = no1 - no2;
            String result=String.valueOf(res);
            jTextField6.setText(result);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Enter appropriate values");

        }   */   // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSUBTRACTActionPerformed

    private void jButtonDIVIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDIVIDEActionPerformed
        NumEnter1 = Double.parseDouble(jTextArea1.getText());
        jTextArea1.setText("");
        op = "/";
        /*try{
            String a = jTextField4.getText();// TODO add your handling code here:
            String b = jTextField5.getText();
            int no1=Integer.parseInt(a);
            int no2=Integer.parseInt(b);

            int res = no1 / no2;
            String result=String.valueOf(res);
            jTextField6.setText(result);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Enter appropriate values");

        }  */    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDIVIDEActionPerformed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        NumEnter1 = Double.parseDouble(jTextArea1.getText());
        jTextArea1.setText("");
        op = "+";/*try{
            String a = jTextField4.getText();// TODO add your handling code here:
            String b = jTextField5.getText();
            int no1=Integer.parseInt(a);
            int no2=Integer.parseInt(b);

            int res = no1 + no2;
            String result=String.valueOf(res);
            jTextField6.setText(result);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Enter appropriate values");

        }*/
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
jTextField1.setText(String.valueOf(NumEnter1));        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JButton jButtonDECIMAL;
    private javax.swing.JButton jButtonDIVIDE;
    private javax.swing.JButton jButtonMULTIPLY;
    private javax.swing.JButton jButtonNUM0;
    private javax.swing.JButton jButtonNUM1;
    private javax.swing.JButton jButtonNUM2;
    private javax.swing.JButton jButtonNUM3;
    private javax.swing.JButton jButtonNUM4;
    private javax.swing.JButton jButtonNUM5;
    private javax.swing.JButton jButtonNUM6;
    private javax.swing.JButton jButtonNUM7;
    private javax.swing.JButton jButtonNUM8;
    private javax.swing.JButton jButtonNUM9;
    private javax.swing.JButton jButtonSOLVE;
    private javax.swing.JButton jButtonSUBTRACT;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
