/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.cbt.project.csc.pkg301;

/**
 *
 * @author Samsung
 */
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        init();
        
        
         Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get the current time
                Date currentTime = new Date();

                // Create a SimpleDateFormat object to format the time
                SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd-MM-yyyy  HH:mm:ss"); // Customize the format as needed

                // Format the time as a String and set it to the JLabel
                jDate.setText(sdf.format(currentTime));
            }
        });
        timer.start();
    }
    
      public void init() {
        setImage();
    }

    public void setImage() {
       
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/images/Logo_of_Pan-Atlantic_University.png"));

        Image img1 = icon1.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
       
        
        
        
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/images/computer-test-icon-vector-28853744-removebg-preview.png"));

        Image img2 = icon2.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
       
        jLabel2.setIcon(new ImageIcon(img1));
        jLabel5.setIcon(new ImageIcon(img2));
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jGetStarted = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20-years.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(776, 600));
        jLabel4.setMinimumSize(new java.awt.Dimension(776, 600));
        jLabel4.setPreferredSize(new java.awt.Dimension(776, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(776, 600));
        setMinimumSize(new java.awt.Dimension(776, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(776, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jGetStarted.setBackground(new java.awt.Color(0, 0, 0));
        jGetStarted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jGetStarted.setForeground(new java.awt.Color(255, 255, 255));
        jGetStarted.setText("Get Started");
        jGetStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetStartedActionPerformed(evt);
            }
        });
        getContentPane().add(jGetStarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 140, 50));

        jExit.setBackground(new java.awt.Color(255, 0, 0));
        jExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jExit.setForeground(new java.awt.Color(255, 255, 255));
        jExit.setText("Exit");
        jExit.setMaximumSize(new java.awt.Dimension(121, 33));
        jExit.setMinimumSize(new java.awt.Dimension(121, 33));
        jExit.setPreferredSize(new java.awt.Dimension(121, 33));
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 140, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Computer-Based Testing (CBT) Application");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 570, 80));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 250, 260));

        jDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 13, 195, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20-years.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit?","Select",JOptionPane.YES_NO_OPTION);
        
        if (a==0){
            this.dispose();
        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jGetStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGetStartedActionPerformed
        this.dispose();
        new Login().setVisible(true);
        
    }//GEN-LAST:event_jGetStartedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDate;
    private javax.swing.JButton jExit;
    private javax.swing.JButton jGetStarted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
